"""
Tests — Contrato Pydantic Capa 00: RawInboundEvent
TS_000_001_CONTRATO_RAW_INBOUND_EVENT

Valida el contrato definido en app/contracts/inbound_contract.py.

Cobertura requerida:
  1. Construir RawInboundEvent con texto libre.
  2. Construir RawInboundEvent con archivo.
  3. event_id se autogenera y es UUID válido.
  4. received_at se autogenera.
  5. processing_status default es PENDING.
  6. Falla si no hay ningún contenido ni metadata.
  7. Falla si raw_content_type=text sin raw_text.
  8. Falla si raw_file_size_bytes es negativo.
"""

import uuid
from datetime import datetime, timezone

import pytest
from pydantic import ValidationError

from app.contracts.inbound_contract import RawInboundEvent


# ---------------------------------------------------------------------------
# Test 1: Construir RawInboundEvent con texto libre
# ---------------------------------------------------------------------------


def test_build_with_text():
    """RawInboundEvent con texto libre debe construirse sin errores."""
    event = RawInboundEvent(
        channel="telegram",
        source_type="human",
        raw_content_type="text",
        raw_text="No sé cuánto stock tengo. Paulita tiene un Excel.",
    )

    assert event.channel == "telegram"
    assert event.source_type == "human"
    assert event.raw_content_type == "text"
    assert event.raw_text == "No sé cuánto stock tengo. Paulita tiene un Excel."
    assert event.processing_status == "PENDING"
    assert event.raw_file_ref is None
    assert event.raw_audio_ref is None
    assert event.raw_image_ref is None


# ---------------------------------------------------------------------------
# Test 2: Construir RawInboundEvent con archivo
# ---------------------------------------------------------------------------


def test_build_with_file():
    """RawInboundEvent con archivo debe construirse sin errores."""
    event = RawInboundEvent(
        channel="telegram",
        source_type="human",
        raw_content_type="file",
        raw_file_ref="storage://uploads/stock_mayo_paulita.xlsx",
        raw_file_name="stock_mayo_paulita.xlsx",
        raw_file_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        raw_file_size_bytes=24576,
    )

    assert event.raw_content_type == "file"
    assert event.raw_file_ref == "storage://uploads/stock_mayo_paulita.xlsx"
    assert event.raw_file_name == "stock_mayo_paulita.xlsx"
    assert event.raw_file_size_bytes == 24576
    assert event.raw_text is None


# ---------------------------------------------------------------------------
# Test 3: event_id se autogenera y es UUID válido
# ---------------------------------------------------------------------------


def test_event_id_autogenerated_is_valid_uuid():
    """event_id debe autogenerarse como UUID v4 válido si no se pasa."""
    event = RawInboundEvent(
        channel="whatsapp",
        source_type="human",
        raw_content_type="text",
        raw_text="Hola",
    )

    assert event.event_id != ""
    assert len(event.event_id) == 36  # UUID con guiones
    # Debe ser parseable como UUID
    parsed = uuid.UUID(event.event_id)
    assert str(parsed) == event.event_id


def test_event_id_explicit_is_preserved():
    """Si se pasa event_id explícito, debe preservarse."""
    custom_id = str(uuid.uuid4())
    event = RawInboundEvent(
        event_id=custom_id,
        channel="web",
        source_type="human",
        raw_content_type="text",
        raw_text="Mensaje con ID explícito",
    )
    assert event.event_id == custom_id


def test_two_events_have_different_event_ids():
    """Dos eventos sin event_id explícito deben tener IDs distintos."""
    e1 = RawInboundEvent(
        channel="telegram",
        source_type="human",
        raw_content_type="text",
        raw_text="Mensaje 1",
    )
    e2 = RawInboundEvent(
        channel="telegram",
        source_type="human",
        raw_content_type="text",
        raw_text="Mensaje 2",
    )
    assert e1.event_id != e2.event_id


# ---------------------------------------------------------------------------
# Test 4: received_at se autogenera
# ---------------------------------------------------------------------------


def test_received_at_autogenerated():
    """received_at debe autogenerarse como datetime UTC si no se pasa."""
    before = datetime.now(timezone.utc)
    event = RawInboundEvent(
        channel="api",
        source_type="system",
        raw_content_type="json",
        metadata={"source": "webhook_test"},
    )
    after = datetime.now(timezone.utc)

    assert event.received_at is not None
    assert isinstance(event.received_at, datetime)
    assert before <= event.received_at <= after


# ---------------------------------------------------------------------------
# Test 5: processing_status default es PENDING
# ---------------------------------------------------------------------------


def test_processing_status_default_is_pending():
    """processing_status debe ser PENDING por defecto."""
    event = RawInboundEvent(
        channel="telegram",
        source_type="human",
        raw_content_type="text",
        raw_text="Texto de prueba",
    )
    assert event.processing_status == "PENDING"


def test_processing_status_can_be_set_explicitly():
    """processing_status puede establecerse explícitamente."""
    event = RawInboundEvent(
        channel="telegram",
        source_type="human",
        raw_content_type="text",
        raw_text="Texto de prueba",
        processing_status="DELIVERED",
    )
    assert event.processing_status == "DELIVERED"


# ---------------------------------------------------------------------------
# Test 6: Falla si no hay ningún contenido ni metadata
# ---------------------------------------------------------------------------


def test_fails_without_any_content_or_metadata():
    """Debe fallar si no hay raw_text, raw_file_ref, raw_audio_ref, raw_image_ref ni metadata."""
    with pytest.raises(ValidationError, match="al menos uno"):
        RawInboundEvent(
            channel="telegram",
            source_type="human",
            raw_content_type="otro",
            # sin raw_text, raw_file_ref, raw_audio_ref, raw_image_ref
            # metadata vacío por defecto
        )


def test_passes_with_only_metadata():
    """Debe pasar si solo hay metadata no vacía."""
    event = RawInboundEvent(
        channel="api",
        source_type="webhook",
        raw_content_type="json",
        metadata={"event_type": "payment_received", "amount": 5000},
    )
    assert event.metadata["event_type"] == "payment_received"


# ---------------------------------------------------------------------------
# Test 7: Falla si raw_content_type=text sin raw_text
# ---------------------------------------------------------------------------


def test_fails_text_content_type_without_raw_text():
    """raw_content_type='text' sin raw_text debe fallar."""
    with pytest.raises(ValidationError, match="raw_text"):
        RawInboundEvent(
            channel="telegram",
            source_type="human",
            raw_content_type="text",
            # raw_text ausente
        )


def test_fails_file_content_type_without_raw_file_ref():
    """raw_content_type='file' sin raw_file_ref debe fallar."""
    with pytest.raises(ValidationError, match="raw_file_ref"):
        RawInboundEvent(
            channel="telegram",
            source_type="human",
            raw_content_type="file",
            raw_file_name="archivo.xlsx",
            # raw_file_ref ausente
        )


def test_fails_audio_content_type_without_raw_audio_ref():
    """raw_content_type='audio' sin raw_audio_ref debe fallar."""
    with pytest.raises(ValidationError, match="raw_audio_ref"):
        RawInboundEvent(
            channel="whatsapp",
            source_type="human",
            raw_content_type="audio",
            # raw_audio_ref ausente
        )


def test_fails_image_content_type_without_raw_image_ref():
    """raw_content_type='image' sin raw_image_ref debe fallar."""
    with pytest.raises(ValidationError, match="raw_image_ref"):
        RawInboundEvent(
            channel="telegram",
            source_type="human",
            raw_content_type="image",
            # raw_image_ref ausente
        )


# ---------------------------------------------------------------------------
# Test 8: Falla si raw_file_size_bytes es negativo
# ---------------------------------------------------------------------------


def test_fails_negative_file_size():
    """raw_file_size_bytes negativo debe fallar."""
    with pytest.raises(ValidationError, match="negativo"):
        RawInboundEvent(
            channel="telegram",
            source_type="human",
            raw_content_type="file",
            raw_file_ref="storage://uploads/archivo.pdf",
            raw_file_size_bytes=-1,
        )


def test_zero_file_size_is_valid():
    """raw_file_size_bytes = 0 es válido (archivo vacío)."""
    event = RawInboundEvent(
        channel="api",
        source_type="system",
        raw_content_type="file",
        raw_file_ref="storage://uploads/empty.txt",
        raw_file_size_bytes=0,
    )
    assert event.raw_file_size_bytes == 0


# ---------------------------------------------------------------------------
# Tests adicionales de campos opcionales y canales
# ---------------------------------------------------------------------------


def test_optional_fields_default_to_none():
    """Los campos opcionales deben ser None por defecto."""
    event = RawInboundEvent(
        channel="cli",
        source_type="human",
        raw_content_type="text",
        raw_text="Comando de prueba",
    )
    assert event.conversation_id is None
    assert event.user_id is None
    assert event.cliente_id is None
    assert event.raw_file_ref is None
    assert event.raw_file_name is None
    assert event.raw_file_type is None
    assert event.raw_file_size_bytes is None
    assert event.raw_audio_ref is None
    assert event.raw_image_ref is None


def test_all_channels_accepted():
    """Todos los canales válidos deben ser aceptados."""
    for channel in ("telegram", "whatsapp", "web", "api", "email", "cli", "otro"):
        event = RawInboundEvent(
            channel=channel,  # type: ignore[arg-type]
            source_type="human",
            raw_content_type="text",
            raw_text="Prueba de canal",
        )
        assert event.channel == channel


def test_invalid_channel_rejected():
    """Canal inválido debe ser rechazado."""
    with pytest.raises(ValidationError):
        RawInboundEvent(
            channel="signal",  # type: ignore[arg-type]
            source_type="human",
            raw_content_type="text",
            raw_text="Prueba",
        )


def test_document_content_type_requires_file_ref():
    """raw_content_type='document' también requiere raw_file_ref."""
    with pytest.raises(ValidationError, match="raw_file_ref"):
        RawInboundEvent(
            channel="email",
            source_type="human",
            raw_content_type="document",
            raw_file_name="factura.pdf",
            # raw_file_ref ausente
        )

    # Con raw_file_ref debe pasar
    event = RawInboundEvent(
        channel="email",
        source_type="human",
        raw_content_type="document",
        raw_file_ref="storage://uploads/factura.pdf",
        raw_file_name="factura.pdf",
    )
    assert event.raw_content_type == "document"
